### ISSUE TITLE
Gnu stow replacement

### ISSUE THREAD

**Issue by 573** [aviaviavi/confetti#1]
Could it be used as a replacement for gnu stow?

**Comment by aviaviavi** [comment]
In it's current form, it definitely does not have enough functionality to be a full stow replacement. I should say that was never my intention for this tool. The main advantage it has is being able to swap multiple files in tandem, and being able to configure it so the commands you issue are very simple. 

However, with enough work put in, it definitely could morph into something that could replace stow. Confetti definitely needs the ability to specify arbitrary locations for the config variants. The main thing I'm unsure of is if there's a sufficient reason that confetti would be _better_ than stow at doing what it does, and I'm unsure if that would be the case. As of now, stow and confetti can both be used side by side, they do _slightly_ different things.

**Comment by aviaviavi** [comment]
Been considering adding a few features that could bring it further in this direction. I'm thinking:

- For each group, a user could configure `variant_paths` each would specify `path :: string` and optionally `recursive :: bool`. confetti would then search for matching spec file(s) in the given path(s).
- add option for the null variant, ie link the version of the target file to a variant with the same name (which would obviously require a `variant_path` to be specified).

@573 Let me know what you think, or if you have different use cases for stow that I'm not addressing.

**Comment by aviaviavi** [comment]
I think the latest release of 0.0.2 gets us a big step in this direction. I'll just leave this issue open for a bit longer in case there are any specific requests along this line of thinking, and close it if it remains inactive.
